%LET _CLIENTTASKLABEL='Outliers';
%LET _CLIENTPROCESSFLOWNAME='Process Flow';
%LET _CLIENTPROJECTPATH='\\pgcw01fscl03\Users$\FKU838\Documents\Projects\opod\opod.egp';
%LET _CLIENTPROJECTNAME='opod.egp';
%LET _SASPROGRAMFILE=;

GOPTIONS ACCESSIBLE;
proc sql;
create table FKU838SL.OPOD_OUTLIER_LIMITS as
select INGREDIENT, sum(Claims) as Claims,
	max(STRENGTH) as MAX_STRENGTH,
	max(STRENGTH)*18 as UPPER_LIMIT,
	min(STRENGTH) as MIN_STRENGTH,
	min(STRENGTH)/4 as LOWER_LIMIT
from FKU838SL.OPOD_GGSSI
where Remove <> 'x' and Claims > 10
group by INGREDIENT;

create unique index INGREDIENT
on FKU838SL.OPOD_OUTLIER_LIMITS (INGREDIENT);
quit;

GOPTIONS NOACCESSIBLE;
%LET _CLIENTTASKLABEL=;
%LET _CLIENTPROCESSFLOWNAME=;
%LET _CLIENTPROJECTPATH=;
%LET _CLIENTPROJECTNAME=;
%LET _SASPROGRAMFILE=;

